version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  redis:
    image: redis
    container_name: redis
    command: redis-server
    ports:
      - "6379:6379"
  celery_worker:
    build: .
    command: celery -A techprices worker -l INFO
    depends_on:
      - redis
      - web
      - db
  celery_beat:
    build: .
    command: celery -A techprices beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - redis
      - web
      - db