# Generated by Django 3.1.5 on 2021-01-09 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20210110_0202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TechnoDom',
        ),
        migrations.CreateModel(
            name='TechnoDom',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tracker.shop',),
        ),
    ]
