# Generated by Django 3.1.5 on 2021-01-12 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20210110_0533'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BelyiVeter',
        ),
        migrations.DeleteModel(
            name='Mechta',
        ),
        migrations.DeleteModel(
            name='Sulpak',
        ),
        migrations.DeleteModel(
            name='TechnoDom',
        ),
    ]
