# Generated by Django 3.1.5 on 2021-01-21 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20210112_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='product',
        ),
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashes', to='tracker.category')),
            ],
        ),
        migrations.AddField(
            model_name='price',
            name='hash',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='tracker.hash'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='hash',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tracker.hash'),
            preserve_default=False,
        ),
    ]
